# Generated by Django 4.2.7 on 2025-06-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('intro', models.TextField(verbose_name='简介')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('cover_image', models.URLField(max_length=255, verbose_name='封面图URL')),
                ('location', models.CharField(help_text='格式：纬度,经度', max_length=100, verbose_name='地理位置')),
                ('opening_hours', models.CharField(max_length=255, verbose_name='开放时间')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='票价')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
                'ordering': ['village', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='乡村名称')),
                ('intro', models.TextField(verbose_name='简介')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('cover_image', models.URLField(max_length=255, verbose_name='封面图URL')),
                ('location', models.CharField(help_text='格式：纬度,经度', max_length=100, verbose_name='地理位置')),
                ('features', models.TextField(blank=True, help_text='JSON格式', verbose_name='特色标签')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='平均评分')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='regions.region', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '乡村',
                'verbose_name_plural': '乡村',
                'ordering': ['-is_recommended', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VillageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255, verbose_name='图片URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='图片说明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='villages.village', verbose_name='乡村')),
            ],
            options={
                'verbose_name': '乡村图库',
                'verbose_name_plural': '乡村图库',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AttractionGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255, verbose_name='图片URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='图片说明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='villages.attraction', verbose_name='景点')),
            ],
            options={
                'verbose_name': '景点图库',
                'verbose_name_plural': '景点图库',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='villages.village', verbose_name='所属乡村'),
        ),
    ]
