# Generated by Django 4.2.7 on 2025-06-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='民宿名称')),
                ('property_type', models.CharField(choices=[('house', '独栋房屋'), ('apartment', '公寓'), ('farm', '农场'), ('guesthouse', '客栈')], max_length=20, verbose_name='物业类型')),
                ('address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('location', models.CharField(help_text='格式：纬度,经度', max_length=100, verbose_name='地理位置')),
                ('intro', models.TextField(verbose_name='简介')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('cover_image', models.URLField(max_length=255, verbose_name='封面图URL')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='平均评分')),
                ('orders_count', models.IntegerField(default=0, verbose_name='订单数')),
                ('lowest_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低价格')),
                ('features', models.TextField(blank=True, help_text='JSON格式', verbose_name='设施特色')),
                ('check_in_time', models.CharField(default='14:00', max_length=50, verbose_name='入住时间')),
                ('check_out_time', models.CharField(default='12:00', max_length=50, verbose_name='退房时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否特色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homestays', to=settings.AUTH_USER_MODEL, verbose_name='所属商户')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homestays', to='villages.village', verbose_name='所属乡村')),
            ],
            options={
                'verbose_name': '民宿',
                'verbose_name_plural': '民宿',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='房型名称')),
                ('cover_image', models.URLField(max_length=255, verbose_name='封面图URL')),
                ('area', models.IntegerField(verbose_name='面积(㎡)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='优惠价')),
                ('bed_type', models.CharField(choices=[('single', '单人床'), ('double', '双人床'), ('queen', '大床'), ('king', '特大床'), ('bunk', '上下铺'), ('sofa', '沙发床')], max_length=20, verbose_name='床型')),
                ('max_guests', models.IntegerField(verbose_name='最大入住人数')),
                ('room_count', models.IntegerField(verbose_name='房间数量')),
                ('description', models.TextField(verbose_name='房型描述')),
                ('facilities', models.TextField(blank=True, help_text='JSON格式', verbose_name='设施')),
                ('breakfast', models.BooleanField(default=False, verbose_name='含早餐')),
                ('cancellation', models.CharField(blank=True, max_length=255, verbose_name='取消政策')),
                ('status', models.CharField(choices=[('active', '上架'), ('inactive', '下架')], default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='homestays.homestay', verbose_name='所属民宿')),
            ],
            options={
                'verbose_name': '房间类型',
                'verbose_name_plural': '房间类型',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='RoomGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255, verbose_name='图片URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='图片说明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='homestays.roomtype', verbose_name='房型')),
            ],
            options={
                'verbose_name': '房间图库',
                'verbose_name_plural': '房间图库',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomestayGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255, verbose_name='图片URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='图片说明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='homestays.homestay', verbose_name='民宿')),
            ],
            options={
                'verbose_name': '民宿图库',
                'verbose_name_plural': '民宿图库',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('available', models.IntegerField(verbose_name='可用数量')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='homestays.roomtype', verbose_name='房型')),
            ],
            options={
                'verbose_name': '房间库存',
                'verbose_name_plural': '房间库存',
                'ordering': ['date'],
                'unique_together': {('room_type', 'date')},
            },
        ),
    ]
