# Generated by Django 4.2.7 on 2025-06-14 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homestays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomestayReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='评分')),
                ('comment', models.TextField(verbose_name='评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='homestays.homestay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '民宿评价',
                'verbose_name_plural': '民宿评价',
            },
        ),
    ]
