# Generated by Django 4.2.7 on 2025-06-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='区域编码')),
                ('level', models.CharField(choices=[('province', '省'), ('city', '市'), ('county', '县/区')], max_length=10, verbose_name='级别')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=10, verbose_name='状态')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='regions.region', verbose_name='上级区域')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'ordering': ['code'],
            },
        ),
    ]
