# Generated by Django 4.2.7 on 2025-06-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('villages', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='美食名称')),
                ('cover_image', models.URLField(max_length=255, verbose_name='封面图URL')),
                ('intro', models.TextField(verbose_name='简介')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='优惠价')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='平均评分')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('ingredients', models.TextField(blank=True, verbose_name='食材配料')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '美食',
                'verbose_name_plural': '美食',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='特产名称')),
                ('cover_image', models.URLField(max_length=255, verbose_name='封面图URL')),
                ('intro', models.TextField(verbose_name='简介')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='优惠价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='平均评分')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('specs', models.TextField(blank=True, help_text='JSON格式', verbose_name='规格参数')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '特产',
                'verbose_name_plural': '特产',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('type', models.CharField(choices=[('product', '特产'), ('food', '美食')], max_length=10, verbose_name='类型')),
                ('icon', models.URLField(blank=True, max_length=255, verbose_name='图标URL')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品类别',
                'verbose_name_plural': '产品类别',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255, verbose_name='图片URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='图片说明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product', verbose_name='特产')),
            ],
            options={
                'verbose_name': '特产图库',
                'verbose_name_plural': '特产图库',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='所属类别'),
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='所属商户'),
        ),
        migrations.AddField(
            model_name='product',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='villages.village', verbose_name='所属乡村'),
        ),
        migrations.CreateModel(
            name='FoodGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255, verbose_name='图片URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='图片说明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.food', verbose_name='美食')),
            ],
            options={
                'verbose_name': '美食图库',
                'verbose_name_plural': '美食图库',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='products.productcategory', verbose_name='所属类别'),
        ),
        migrations.AddField(
            model_name='food',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL, verbose_name='所属商户'),
        ),
        migrations.AddField(
            model_name='food',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='villages.village', verbose_name='所属乡村'),
        ),
    ]
